# Generated by Django 4.2.2 on 2023-08-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_host_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="is_host", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user", name="name", field=models.CharField(max_length=150),
        ),
    ]
