# Generated by Django 4.2.2 on 2023-08-22 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_room_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity", options={"verbose_name_plural": "Amenities"},
        ),
    ]
