databases:
  - name: airbnbcloneDB
    plan: free
    databaseName: airbnbclone
    user: airbnbclone
    region: singapore

services:
  - type: web
    plan: free
    name: airbnb-clone-backend
    region: singapore
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn config.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airbnbcloneDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
