# Generated by Django 4.2.2 on 2024-01-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0003_photo_delete_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo", name="file", field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="video", name="file", field=models.URLField(),
        ),
    ]
